apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
      - name: leaderboard
        image: yourdockerhubusername/leaderboard-service:v1
        ports:
        - containerPort: 3000